version: 0.0.{build}
shallow_clone: true
clone_depth: 1

environment:
    pack_dlls: 1
    PROJECT_NAME: "steam_achievement_stats_watcher"
    GITHUB_TOKEN: "CX6oVGywKQDDate+0y9tZ2OEmKtxBeKuf/7AMCXmFkLlQpREQt3tihO3oGdzChUU"
    matrix:
        - PYTHON: "C:\\Python37"
          ARCH: "32"
        - PYTHON: "C:\\Python37"
          ARCH: "64"

install:
    - "%PYTHON%\\python.exe --version"
    - "%PYTHON%\\Scripts\\pip install --no-warn-script-location pyinstaller"
    - ps: Set-Content "$env:PROJECT_NAME\\version.py" ( "__version__ = '{0}'" -f ( $env:APPVEYOR_BUILD_VERSION ) )
    - "%PYTHON%\\Scripts\\pip install --no-warn-script-location -r requirements.txt"

build:
  verbosity: normal

build_script:
    - "%PYTHON%\\Scripts\\pyinstaller --onefile --icon icon.ico main.py"

after_build:
  - ps: 7z a $env:PROJECT_NAME-$env:APPVEYOR_BUILD_VERSION-windows-$env:ARCH.zip .\dist\* LICENSE

artifacts:
    - path: "*.zip"

deploy:
  ################################################################################
  # Release untagged versaions as drafts
  - provider: GitHub
    release: draft-v$(appveyor_build_version)
    auth_token:
      secure: $GITHUB_TOKEN
    artifact: "*.zip"
    draft: true
    prerelease: false
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: false

  ################################################################################
  # Release tagged versaions as pre-release
  - provider: GitHub
    release: v$(appveyor_build_version)
    auth_token:
      secure: $GITHUB_TOKEN
    artifact: "*.zip"
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true